### ISSUE TITLE
Allow additional ingresses

### ISSUE THREAD

**Issue by ncasaux** [pajikos/home-assistant-helm-chart#109]
Hello @pajikos !

Firstly, thank you for this amazing Helm Chart. I've been using it for some months now and I'm really happy about it and all the automatic updates ! 👍

Secondly, I was wondering if you could consider adding the possibility to add extra ingresses, like you did already for ports and services ?

My use case is that I need an ingress to forward trafic on path `/notify` (without specific host because of DLNA limitations) to HASS [DLNA Digital Media Renderer] (https://www.home-assistant.io/integrations/dlna_dmr) integration.

My ingress looks like this, and as per my understanding, I can't set it up using the current structure of `values.yaml` and `ingress.yaml` files.

```yaml
spec:
  rules:
    - http:
        paths:
          - path: /notify
            pathType: Prefix
            backend:
              service:
                name: dlna
                port:
                  number: 5555
```

Would you considerer adding the possibility to add extra ingresses in `values.yaml` file ?

Thanks in advance!
