### ISSUE TITLE
 Error converting YAML to JSON when using additionalVolumes

### ISSUE THREAD

**Issue by tenondra** [pajikos/home-assistant-helm-chart#34]
Hi, I encountered issue with error message: `Error: UPGRADE FAILED: YAML parse error on home-assistant/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 53: did not find expected key`
I tried looing into the `statefulset.yaml` but found nothing suspicious on related lines
my values.yaml are almost default, and work without specifing additional volumes/mounts (I do this for the zigbee dongle).

The specific values causing issues are:
```
additionalVolumes:
  - hostPath:
      path: >-
        /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_1e174f6d9de5ed118383606262c613ac-if00-port0
      type: CharDevice
    name: usb

additionalMounts:
   - mountPath: /dev/ttyUSB0
     name: usb
```

**Comment by pajikos** [comment]
Hi, please double-check your indentation, especially your additionalMounts, it seems there are two extra spaces on each line.

**Comment by tenondra** [comment]
thanks for the quick response. I double-checked it, but I use autoformatters, and would be unlikely. Anyway, it was not it.

**Comment by pajikos** [comment]
Ok, it looks like I misread, now I see it seems to be correct. Try this one, this is my current working setup. Just to be sure, that the problem is still the same.
You can use my dongle path, we need to test the yaml parser inside Helm.
```yaml
additionalVolumes:
  - hostPath:
      type: CharDevice
      path: >-
        /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230509111242-if00
    name: usb

# if you need any additional volume mounts, you can define them here
additionalMounts:
  - mountPath: /dev/ttyACM0
    name: usb
```
