### ISSUE TITLE
Support for prometheus

### ISSUE THREAD

**Issue by jlpedrosa** [pajikos/home-assistant-helm-chart#39]
Hi!

One question, what do you think about adding an optional object to enable the prometheus scraping of home assistant?
Something among the lines of:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    hommeassistant: prometheus
  name: prometheus
  namespace: prometheus
spec:
  endpoints:
  - interval: 30s
    targetPort: 8321
    path: /api/prometheus
  namespaceSelector:
    matchNames:
    - homeassistant
  selector:
    matchLabels:
      homeassistant-label: "true"
 ```
 
 If you think it's a good Idea I can create a PR if you have appetite for contribs.
