### ISSUE TITLE
How to enable persistence?

### ISSUE THREAD

**Issue by softlylove** [pajikos/home-assistant-helm-chart#83]
Hello,

Thank you for the chart! I've successfully installed it 🎉

However, I encountered an error message after enabling persistence.

```
Error: UPGRADE FAILED: cannot patch "home-assistant" with kind StatefulSet: StatefulSet.apps "home-assistant" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

I've tried searching for a solution, but I'm still not sure how to resolve the issue. Here are my config:

```yaml
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  existingVolume: ""
  matchExpressions: {}
  matchLabels: {}
  size: 5Gi
  storageClass: ""
```

**Comment by 98jan** [comment]
for me it worked to add following part to the values.yaml:

```
  persistence:
    enabled: true
    size: 25Gi
    storageClass: longhorn
```

Could it be that you already have an existing pvc? Looks like it tries to update an existing field which is not allowed to be updated.
