### ISSUE TITLE
Enabling configuration of COAP service

### ISSUE THREAD

**Issue by dannyyy** [pajikos/home-assistant-helm-chart#88]
Hi,

I'm currently migrating from the outdated `k8s-at-home` helm chart to this one. Thank you very much for providing a new, up-to-date Helm chart to the community.

Since my Kubernetes network is isolated from my smart home and other networks, I need to expose the COAP service. Would be nice if this service exposure could be enabled / configured directly in the Helm chart.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-coap
spec:
  externalTrafficPolicy: Local
  ports:
  - name: coap
    port: 5683
    protocol: UDP
    targetPort: coap
  selector:
    app.kubernetes.io/name: home-assistant
  type: <NodePort|LoadBalancer>
  externalIPs: []
```
