### ISSUE TITLE
ingress path does not seem to work

### ISSUE THREAD

**Issue by nickcw123** [pajikos/home-assistant-helm-chart#94]
When I try and enable ingress

```
ingress:
  enabled: true

  hosts:
    -  host: my-host
       paths:
         - path: /home
           pathType: ImplementationSpecific
```

When I go to the URL
http://my-host/home
the webrowser url changes to
http://my-host/onboarding.html
and gives 404 Not found nginx.

I have tried

```
  annotations:
    className: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

  hosts:
    -  host: my-host
       paths:
         - path: /home
           pathType: ImplementationSpecific
```

and 

```
  annotations:
    className: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  hosts:
    -  host: my-host
       paths:
         - path: /home(/|$)(.*)
           pathType: ImplementationSpecific
```

But I keep getting the same result. 

I would expect the web browser url to goto
http://my-host/home/onboarding.html

Any tips on how to set up so I can reach home assistant from the /home folder would be good.
I am doing this as I want to have 
http://my-host/home
http://my-host/grafana
Using the same tls.

I should say I can get things working if the path is just / So I know everything else like trusted proxises is set up correctyl.

I am using the command 
microk8s helm delete home-assistant  && microk8s helm -f ha.yaml install home-assistant pajikos/home-assistant
to update to make sure everything is clean. 

I have been trying for 2 days now and just cant work out what  the problem is so any help and tips would be really helpful thanks.

**Comment by pajikos** [comment]
Hi,
try to use this:
 ```yaml
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: my-host
      paths:
        - path: /home(/|$)(.*)
          pathType: Prefix
  
 ```
 which:
 * enables using regex in nginx
 * Using different pathType
 
I generally recommend using subdomains instead of subpaths. You would save a lot of time in the future when trying to set up other apps.I found many issues on HA forum when trying to run Home Assistant on a subpath. You may need to configure additional settings because when using rewrite, Home Assistant does not know that it is running on a subpath, so some links may be broken.
 homeassistant:
  external_url: "https://my-host/home/"
  internal_url: "http://192.168.1.2:8123"
